const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const source=fs.readFileSync(__dirname+'/../agent_fronted/src/views/filing-change-review/FilingChangeReviewSession.vue','utf8');
const script=source.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/import[\s\S]*?from\s+['"][^'"]+['"];?/g,'').replace('export default','module.exports =');
const context={module:{exports:{}},StabilityLimitDetails:{},ParseReviewPanel:{},MarkdownIt:function(){this.render=x=>x;},setTimeout,clearTimeout};
vm.runInNewContext(script,context);const c=context.module.exports;
const p={...c.data(),projectId:'p'};
p.attemptState=c.methods.attemptState.bind(p);
p.formParseAttempt={content_status:'success'};
p.filingParseTaskStates={'application-form':{bound_project_id:'p',status:'failed',message:'empty'},'submission:s':{status:'running'}};
assert.equal(c.computed.currentFormParseState.call(p).status,'failed');
assert.deepEqual(Object.keys(c.computed.nonFormParseTaskStates.call(p)),['submission:s']);
p.filingParseTaskStates['application-form'].status='running';
assert.equal(c.computed.currentFormParseState.call(p).status,'running');
p.filingParseTaskStates['application-form'].bound_project_id='old';
assert.equal(c.computed.currentFormParseState.call(p).status,'completed');
p.filingParseTaskStates={};p.formParseAttempt={content_status:'failed'};
assert.equal(c.computed.currentFormParseState.call(p).status,'failed');
p.filingParseTaskStates={'application-form':{project_id:'p',status:'running'}};
assert.equal(c.computed.currentFormParseState.call(p).status,'running');
assert.match(source,/v-for="\(state, key\) in nonFormParseTaskStates"/);
assert.equal((source.match(/:title="parseAttemptLabel\(currentFormParseState\)"/g)||[]).length,1);
console.log('PASS: one form notice, active attempt wins, reload fallback, stale project excluded, other tasks retained');

// 紧凑摘要不重复按钮文字；300条原文证据仍可从详情分组完整访问。
const errors=Array.from({length:300},(_,i)=>({page:1+(i%100),stage:'field_region_unassigned',text:`合成证据${i}`,bbox_pdf:[i,1,i+1,2]}));
const diagnostics={errors,failed_pages:[1,2]};
const before=JSON.stringify(diagnostics);
assert.equal(c.methods.parseDiagnosticsLabel(diagnostics),'100页需核对，300条诊断');
assert.equal(c.methods.parseDiagnosticsLabel({}),'');
assert.equal(c.methods.parseContentLabel('partial'),'部分成功，存在待核对内容');
assert.equal(c.methods.parseStatusType('partial'),'warning');
for(const name of ['parseContentLabel','parseDiagnosticsLabel','parseAttemptLabel','diagnosticMessage'])p[name]=c.methods[name].bind(p);
c.methods.openParseDetails.call(p,p.attemptState({content_status:'partial',parse_diagnostics:diagnostics}),'合成申请表');
const entries=p.parseDetailGroups.flatMap(g=>g.entries);
assert.equal(entries.length,300);
assert.deepEqual(Array.from(entries,e=>e.text),errors.map(e=>e.text));
assert.deepEqual(Array.from(entries,e=>e.bbox_pdf),errors.map(e=>e.bbox_pdf));
assert.equal(JSON.stringify(diagnostics),before);
assert.doesNotMatch(source,/查看未归属文字和原文位置：第/);
assert.match(source,/<pre v-if="entry.text">\{\{ entry.text \}\}<\/pre>/);
console.log('PASS: compact diagnostic summary retains all 300 evidence entries and original coordinates');
