// 挂载当前会话页申请表的原模板、原方法和 Element UI，调用隔离真实业务服务。
const fs = require('fs');
const path = require('path');
const assert = require('assert/strict');
const { createRequire } = require('module');
const runtime = createRequire(process.env.T3_NODE_PACKAGES + '/package.json');
const source = fs.readFileSync(path.join(__dirname, '../agent_fronted/src/views/filing-change-review/FilingChangeReviewSession.vue'), 'utf8');
const template = '<div style="padding:24px">' + source.split('<el-tab-pane label="申请表" name="form">')[1]?.split('</el-tab-pane>')[0] + '</div>';
if (template.includes('undefined')) throw Error('未找到当前申请表模板');
let script = source.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/import[\s\S]*?from\s+["'][^"']+["'];?/g, '').replace('export default', 'const component =');
const prelude = `const MarkdownIt = function(){this.render=x=>x};
const api = async (url, value) => {const response = await fetch(url, value ? {method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(value)} : {});if(!response.ok)throw Error(await response.text());return response.json()};
const getApplicationForm = () => api('/data');
const saveApplicationForm = (id, data) => api('/save', data);
const startApplicationFormParse = () => api('/parse', {});
const startApplicationFormImport = async(id, data) => (await fetch('/upload', {method:'POST',body:data})).json();
const getFilingParseTaskProgress = id => api('/progress/'+id);
const getFilingProjectParseTasks = ${process.env.T4_BROWSER || process.env.T4_TASKS ? "()=>api('/task-list')" : 'async()=>({data:[]})'};
const getFilingChangeProjectDetail = async()=>({data:{project_name:'T3临时验证'}});
`;
const setup = `
component.template = ${JSON.stringify(template)};
component.created = undefined;component.mounted = undefined;
// 其他标签页不参与本测试；申请表加载、保存、解析轮询、冲突解决使用原方法。
for(const name of ['loadSubmissionCatalog','loadSubmissions','loadReferenceTaxonomy','loadLatestResult','loadRunHistory','loadReferenceMaterials','loadRules','loadReport'])component.methods[name]=async()=>{};
(async()=>{const initial=await api('/data');component.computed.projectId=()=>initial.data.project_id;
window.page = new Vue(component).$mount('#app');window.page.formVisible=true;window.page.loadBaseData();})();`;
fs.writeFileSync('/tmp/t3-page.js', prelude + script + setup);
(async()=>{
  const browser = await runtime('playwright').chromium.launch({headless:true, executablePath:process.env.T3_CHROME || '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome', args:['--no-proxy-server']});
  const page = await browser.newPage({viewport:{width:1200,height:950}});
  page.on('pageerror', e => console.error('PAGE ERROR',e.message));
  await page.goto('http://127.0.0.1:18766');
  if (process.env.T5_BROWSER) {
    const state = async() => (await (await page.request.get('http://127.0.0.1:18766/data')).json()).data;
    const refresh = async() => { await page.reload(); await page.waitForFunction(()=>window.page && !window.page.loading); };
    await page.request.post('http://127.0.0.1:18766/fresh');
    await refresh();
    await page.getByRole('button',{name:'保存申请表',exact:true}).click();
    await page.getByText('申请表已保存',{exact:true}).first().waitFor();
    await refresh();
    await page.getByText(/文件解析：尚未解析/).waitFor();
    assert.equal((await state()).parse_status,'not_parsed');
    assert.equal((await state()).original_file_id,'');
    const generic = page.locator('.el-collapse-item').filter({has:page.locator('.el-collapse-item__header').filter({hasText:'药品通用名称'})});
    await generic.locator('.el-collapse-item__header').click();
    await generic.locator('input').fill('浏览器人工药名');
    await page.getByRole('button',{name:'保存申请表',exact:true}).click();
    await page.getByText('申请表已保存',{exact:true}).first().waitFor();
    await refresh();
    await page.getByText(/文件解析：尚未解析/).waitFor();
    assert.equal((await state()).form_json.item_6_generic_name.value,'浏览器人工药名');
    assert.equal((await state()).form_json.item_6_generic_name.manual_modified,true);
    const upload = async(name,buffer) => {
      await page.locator('input[type=file]').first().setInputFiles({name,mimeType:'application/octet-stream',buffer});
      await page.waitForFunction(()=>!window.page.importingForm && !window.page.savingForm);
      await refresh();
    };
    await upload('坏.pdf',Buffer.from('%PDF-1.7 broken'));
    await page.getByText(/文件解析：尚未解析/).waitFor();
    assert.equal((await state()).latest_attempt.content_status,'failed');
    assert.equal((await state()).original_file_id,'');
    const partial = await (await page.request.get('http://127.0.0.1:18766/partial-pdf')).body();
    await upload('部分内容.pdf',partial);
    await page.getByText(/文件解析：部分成功/).waitFor();
    assert.equal((await state()).parse_status,'partial');
    await page.getByRole('button',{name:'保存申请表',exact:true}).click();
    await page.getByText('申请表已保存',{exact:true}).first().waitFor();
    await refresh();
    await page.getByText(/文件解析：部分成功/).waitFor();
    const original = await (await page.request.get('http://127.0.0.1:18766/original-docx')).body();
    await upload('有效原件.docx',original);
    await page.getByText(/有效原件：有效原件.docx/).waitFor();
    const effective = (await state()).original_file_id;
    await upload('失败替换.pdf',Buffer.from('%PDF-1.7 broken'));
    assert.equal((await state()).original_file_id,effective);
    await page.getByText(/有效原件：有效原件.docx/).waitFor();
    await page.getByRole('button',{name:'重新解析申请表',exact:true}).click();
    await page.waitForFunction(()=>!window.page.importingForm && !window.page.savingForm);
    await refresh();
    await page.getByText(/有效原件：有效原件.docx/).waitFor();
    assert.equal((await state()).latest_attempt.content_status,'success');
    assert.equal((await state()).form_json.item_6_generic_name.value,'浏览器人工药名');
    await page.screenshot({path:'/tmp/five-defects-browser.png'});
    console.log('通过：空表保存和刷新、人工输入、首次坏上传、正常上传、失败替换及重解析；页面文案与真实持久化状态一致。');
    await browser.close();
    return;
  }
  if (process.env.T4_BROWSER) {
    const state = async() => (await (await page.request.get('http://127.0.0.1:18766/data')).json()).data;
    const refresh = async() => {await page.reload(); await page.waitForFunction(()=>window.page && !window.page.loading);};
    const upload = async(route, name) => {
      const buffer = await (await page.request.get('http://127.0.0.1:18766/'+route)).body();
      await page.locator('input[type=file]').first().setInputFiles({name,mimeType:'application/octet-stream',buffer});
      await page.waitForFunction(()=>!window.page.importingForm && !window.page.savingForm);
      assert.equal(await page.evaluate(()=>window.page.filingParseTaskStates['application-form'].status),'completed');
      await refresh();
    };
    const section = async(label) => {
      const node = page.locator('.el-collapse-item').filter({has:page.locator('.el-collapse-item__header').filter({hasText:label})});
      if (!(await node.getAttribute('class')).includes('is-active')) await node.locator('.el-collapse-item__header').click();
      return node;
    };
    await page.request.post('http://127.0.0.1:18766/fresh'); await refresh();
    await upload('four-docx','后置勾选.docx');
    let data = await state();
    assert.equal(data.form_json.item_15_validity_period.reported_value,'24个月');
    assert.equal(data.form_json.item_15_validity_period.sub_fields.proposed_validity_period,'');
    assert.equal(data.form_json.item_3_otc_type.value,'处方药');
    assert.equal(data.form_json.item_30_applicant_info.sub_fields.contact,'张三');
    let otc = await section('是否为OTC');
    await otc.locator('.el-radio').filter({hasText:'非处方药'}).click();
    let party = await section('申请人信息');
    const contact = party.locator('.el-form-item').filter({hasText:'联系人'}).locator('input');
    await contact.fill('人工代表');
    await page.getByRole('button',{name:'保存申请表',exact:true}).click();
    await page.waitForFunction(()=>!window.page.savingForm); await refresh();
    await page.getByRole('button',{name:'重新解析申请表',exact:true}).click();
    await page.waitForFunction(()=>!window.page.importingForm && !window.page.savingForm); await refresh();
    data = await state();
    assert.equal(data.form_json.item_3_otc_type.value,'非处方药');
    assert.equal(data.form_json.item_30_applicant_info.sub_fields.contact,'人工代表');
    assert.equal(data.form_json.item_30_applicant_info.manual_modified,true);
    await upload('four-conflict','待核对.docx');
    const validity = await section('药品有效期');
    await validity.getByText('待核对',{exact:true}).waitFor();
    await validity.locator('summary').filter({hasText:'冲突'}).first().click();
    await validity.getByText(/药品有效期由18个月延长至24个月/).first().waitFor();
    otc = await section('是否为OTC');
    await otc.locator('summary').filter({hasText:'归属冲突'}).waitFor();
    await upload('four-uncertain','无框待核对.pdf');
    await page.getByText(/文件解析：部分成功/).waitFor();
    await page.getByText(/文字已识别，表格结构未恢复/).first().waitFor();
    await page.getByRole('button',{name:'保存申请表',exact:true}).click();
    await page.waitForFunction(()=>!window.page.savingForm); await refresh();
    await page.getByText(/文字已识别，表格结构未恢复/).first().waitFor();
    data = await state();
    assert.equal(data.latest_attempt.content_status,'partial');
    assert.equal(data.effective_source.parse_diagnostics.errors[0].code,'table_structure_unresolved');
    assert.equal(data.form_json.item_3_otc_type.value,'非处方药');
    await page.screenshot({path:'/tmp/four-defects-browser.png'});
    console.log('通过：真实异步上传、月份对象、后置勾选、企业子字段、人工修改保存刷新重解析、冲突原文、无框表未恢复诊断持久化与页面提示。');
    await browser.close(); return;
  }
  await page.getByText('15. 药品有效期', {exact:false}).first().waitFor();
  assert.equal(await page.evaluate(()=>Object.values(window.page.formSchema).some(x=>x.manual_modified)),false);
  const openValidity = async()=>{
    const section=page.locator('.el-collapse-item').filter({has:page.locator('.el-collapse-item__header').filter({hasText:'药品有效期'})});
    if(!(await section.getAttribute('class')).includes('is-active'))await section.locator('.el-collapse-item__header').click();
    return section;
  };
  let section=await openValidity();
  const input=()=>section.locator('.el-form-item').filter({hasText:'原有效期'}).locator('input');
  await input().fill('20个月');
  await page.getByRole('button',{name:'保存申请表',exact:true}).click();
  await page.getByText('申请表已保存',{exact:true}).first().waitFor();
  await page.reload();
  await page.waitForFunction(()=>window.page?.formSchema.item_15_validity_period);
  section=await openValidity();
  assert.equal(await input().inputValue(),'20个月');
  await page.getByRole('button',{name:'重新解析申请表',exact:true}).click();
  await section.getByRole('button',{name:'保留人工值'}).waitFor();
  assert.equal(await input().inputValue(),'20个月');
  await section.getByRole('button',{name:'保留人工值'}).click();
  await page.waitForFunction(()=>!Object.keys(window.page.formSchema.item_15_validity_period.candidates||{}).length);
  await page.reload();await page.waitForFunction(()=>window.page?.formSchema.item_15_validity_period);
  section=await openValidity();assert.equal(await input().inputValue(),'20个月');
  await page.getByRole('button',{name:'重新解析申请表',exact:true}).click();
  await section.getByRole('button',{name:'采用候选值'}).waitFor();
  await section.getByRole('button',{name:'采用候选值'}).click();
  await page.waitForFunction(()=>window.page.formSchema.item_15_validity_period.sub_fields.original_validity_period==='18个月');
  await page.reload();await page.waitForFunction(()=>window.page?.formSchema.item_15_validity_period);
  section=await openValidity();assert.equal(await input().inputValue(),'18个月');
  assert.equal(await page.evaluate(()=>window.page.formSchema.item_15_validity_period.manual_modified),false);
  await section.locator('summary').first().click();
  await page.waitForTimeout(500);
  await section.screenshot({path:'/tmp/t3-browser-verified.png'});
  const result=await page.evaluate(async()=> (await (await fetch('/data')).json()).data);
  assert.notEqual(result.confidence,1);
  assert.equal(result.form_json.item_15_validity_period.resolution_history.length,2);
  console.log('通过：原页面输入、保存、刷新、重新解析、保留人工值、再次刷新、采纳候选、再次刷新及原文查看；真实 SQLite 服务持久化。');
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
