// 组件方法回归仅作补充，不替代生产构建浏览器验收。
const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const source=fs.readFileSync(path.join(__dirname,'../agent_fronted/src/views/filing-change-review/ParseReviewPanel.vue'),'utf8');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b});return {promise,resolve,reject};};
let save=async()=>({data:{revision:1}}), readiness=async()=>({data:{ready:true,blocking_issues:[]}}), image=async()=>({data:{page_bbox:[0,0,100,100]}}), sourceRead=async()=>({data:{}});
const sandbox={module:{exports:{}},getFilingParseReadiness:(...a)=>readiness(...a),getFilingParseReview:(...a)=>sourceRead(...a),getFilingParseReviewPage:(...a)=>image(...a),saveFilingParseReview:(...a)=>save(...a)};
const evidenceSource=fs.readFileSync(path.join(__dirname,'../agent_fronted/src/utils/ocrRecoveryEvidence.js'),'utf8');
vm.runInNewContext(evidenceSource.replace('export function','function'),sandbox);
vm.runInNewContext(source.match(/<script>([\s\S]*?)<\/script>/)[1].replace(/^import .*;$/gm,'').replace('export default','module.exports ='),sandbox);
const options=sandbox.module.exports;
function fixture(){
  const p={...options.data(),projectId:'p1',$emit(){},$message:{success(){},warning(){}},$confirm:async()=>{}};
  for(const [k,fn] of Object.entries(options.methods)) p[k]=fn.bind(p);
  for(const [k,fn] of Object.entries(options.computed)) Object.defineProperty(p,k,{get:fn.bind(p)});
  p.context={source_kind:'submission',doc_id:'d1',revision:0,source_identity:{attempt:'a1'},items:[],original_chunks:[{text:'old'}],issues:[{issue_key:'i1',chunk_index:0,code:'ocr_coverage',page:1,bbox_pdf:[10,20,30,40]}]};
  p.selectedKey='i1';p.preview={page_bbox:[0,0,100,100]};
  p.draft.action='correct_text';p.draft.text='corrected';p.draft.reason='checked original';
  return p;
}
(async()=>{
  {const panel=fixture();panel.context.source_kind='application_form';panel.draft.action='correct_table';
   panel.context.issues[0].repair_bbox_pdf=[0,0,60,40];panel.context.original_chunks[0].tables=[{bbox_pdf:[0,0,60,20]}];
   const field={issue_key:'mixed',chunk_index:0,code:'field_region_crossing',bbox_pdf:[0,0,60,40],field_options:[{item_no:6},{item_no:7}]};
   panel.context.issues.push(field);assert(panel.mixedTableReviewAvailable(field));assert.equal(panel.relatedRepairIssues.length,1);
   panel.toggleRelatedIssue('mixed',true);panel.splitRelatedIssue('mixed',true);
   const entry=panel.draft.related_issues[0];entry.field_assignments[1].source_kind='outside_text';
   let submitted;save=async(...args)=>{submitted=args[3];return {data:{revision:1,resolved_issue_keys:['i1','mixed']}}};
   await panel.save();assert.equal(submitted.items[0].related_issues[0].field_assignments[1].source_kind,'outside_text');
   panel.setIssue('i1');assert.equal(panel.draft.related_issues[0].field_assignments[1].source_kind,'outside_text');
   field.bbox_pdf=[0,0,55,40];assert(!panel.mixedTableReviewAvailable(field));
   panel.context.issues.find(i=>i.issue_key==='mixed').bbox_pdf=field.bbox_pdf;
   assert(panel.expandedTableReviewAvailable(field));
   panel.setRelatedReviewScope('mixed',true);assert(panel.mixedTableReviewAvailable(field));
   assert.equal(panel.draft.related_issues[0].field_text_verified,false);
   await panel.loadImage();await panel.save();assert.equal(submitted.items[0].related_issues[0].review_scope,'complete_repair_region');
   panel.setIssue('i1');assert.equal(panel.draft.related_issues[0].review_scope,'complete_repair_region');
   panel.setRelatedReviewScope('mixed',false);assert(!panel.mixedTableReviewAvailable(field));
   console.log('PASS full mixed region source selection and replay');}
  { const panel=fixture();panel.context.source_kind='application_form';panel.draft.action='correct_table';
    panel.context.issues[0].repair_bbox_pdf=[0,0,70,20];
    panel.context.original_chunks[0].tables=[{bbox_pdf:[0,0,30,20]},{bbox_pdf:[40,0,70,20]}];
    const field={issue_key:'cross',chunk_index:0,code:'field_region_crossing',bbox_pdf:[0,0,70,20],field_options:[{item_no:6},{item_no:12}]};
    panel.context.issues.push(field);assert.deepEqual(Array.from(panel.relatedRepairIssues,i=>i.issue_key),['cross']);
    panel.toggleRelatedIssue('cross',true);panel.splitRelatedIssue('cross',true);
    assert.equal(panel.draft.related_issues[0].field_assignments[0].table_index,null);
    assert.deepEqual(Array.from(panel.relatedTableSources(field),s=>s.index),[0,1]);
    field.bbox_pdf=[10,0,60,20];assert.equal(panel.relatedRepairIssues.length,1);
    assert(!panel.crossTableReviewAvailable(field));assert(!panel.mixedTableReviewAvailable(field));
    assert(panel.expandedTableReviewAvailable(field),'部分问题框只能显式选择完整区域核对，默认仍不得跨界确认');
    console.log('PASS explicit cross-table source selection and partial-boundary exclusion'); }
  { const panel=fixture();panel.context.source_kind='application_form';
    panel.context.issues.push({issue_key:'multi',chunk_index:0,code:'field_region_crossing',bbox_pdf:[11,21,20,30],field_options:[{item_no:6},{item_no:12}]});
    panel.toggleRelatedIssue('multi',true);panel.draft.related_issues[0].reviewed_text='药品通用名称：甲\n规格：3mg';
    panel.draft.related_issues[0].field_text_verified=true;panel.splitRelatedIssue('multi',true);
    let entry=panel.draft.related_issues[0];assert.equal(entry.field_assignments.length,2);assert.equal(entry.field_text_verified,false);
    entry.field_assignments=[{target_item_no:6,reviewed_text:'药品通用名称：甲'},{target_item_no:12,reviewed_text:'规格：3mg'}];entry.field_text_verified=true;
    let payload;save=async(...args)=>{payload=args[3];return {data:{revision:1,resolved_issue_keys:['i1','multi']}}};
    await panel.save();assert.equal(payload.items[0].related_issues[0].field_assignments[1].target_item_no,12);
    panel.setIssue('i1');assert.equal(panel.draft.related_issues[0].field_assignments.length,2);
    panel.splitRelatedIssue('multi',false);entry=panel.draft.related_issues[0];assert.equal(entry.field_assignments,null);assert.equal(entry.field_text_verified,false);assert(entry.reviewed_text.includes('规格'));
    console.log('PASS multi-field related assignment payload, reload and explicit reconfirmation'); }
  { const panel=fixture(); panel.context.source_kind='application_form';
    panel.context.issues[0].code='field_region_crossing';
    panel.context.issues[0].field_options=[{item_no:6,title:'药品通用名称'}];
    panel.context.original_chunks[0].tables=[{bbox_pdf:[0,0,50,50]}];
    panel.context.issues.push({issue_key:'table',chunk_index:0,code:'table_review_required',bbox_pdf:[0,0,50,50]});
    assert(!panel.actions.some(a=>a.value==='correct_text'),'表内字段不能提供必然被后端拒绝的正文覆盖');
    assert.deepEqual(Array.from(panel.tableRepairChoices,i=>i.issue_key),['table']);
    panel.$confirm=async()=>{throw Error('cancel')};
    await panel.selectIssue('table');assert.equal(panel.selectedKey,'i1');assert.equal(panel.draft.text,'corrected');
    panel.context.issues[1].chunk_index=1;assert.equal(panel.tableRepairChoices.length,0);
    panel.context.issues[1].chunk_index=0;panel.context.issues[1].bbox_pdf=[0,0,15,25];
    assert.equal(panel.tableRepairChoices.length,0,'不能跳到只覆盖部分字段的表格');
    console.log('PASS table-bound field routing and draft protection'); }
  { const panel=fixture(); panel.context.source_kind='application_form';
    panel.context.issues.push({issue_key:'field',chunk_index:0,code:'field_region_crossing',bbox_pdf:[11,21,20,30],field_options:[{item_no:31,title:'生产企业'}]});
    assert.equal(panel.relatedRepairIssues.length,1);
    panel.toggleRelatedIssue('field',true);
    const entry=panel.draft.related_issues[0];
    assert.equal(entry.target_item_no,null);assert.equal(entry.field_text_verified,false);
    entry.target_item_no=31;entry.reviewed_text='联系人：合成人';entry.field_text_verified=true;entry.reason='已核对原页完整区域';
    let payload;save=async(...args)=>{payload=args[3];return {data:{revision:1,resolved_issue_keys:['i1','field']}}};
    await panel.save();assert.equal(payload.items[0].related_issues[0].target_item_no,31);
    panel.setIssue('i1');assert.equal(panel.draft.related_issues[0].reviewed_text,'联系人：合成人');
    assert.equal(panel.draft.related_issues[0].field_text_verified,true);
    panel.draft.action='correct_table';assert.equal(panel.relatedRepairIssues.length,0);
    panel.context.issues[0].repair_bbox_pdf=[10,20,30,40];
    panel.context.original_chunks[0].tables=[{bbox_pdf:[21,21,29,39]}];
    assert.equal(panel.relatedRepairIssues.length,1);
    panel.context.original_chunks[0].tables=[{bbox_pdf:[10,20,21,31]}];
    assert.equal(panel.relatedRepairIssues.length,1);
    panel.context.original_chunks[0].tables=[{bbox_pdf:[15,20,21,31]}];
    assert.equal(panel.relatedRepairIssues.length,1);
    assert(!panel.mixedTableReviewAvailable(panel.context.issues.find(i=>i.issue_key==='field')));
    assert.notEqual(panel.draft.related_issues[0].review_scope,'complete_repair_region');
    panel.context.original_chunks[0].tables=[{bbox_pdf:[15,20,35,31]}];
    assert.equal(panel.relatedRepairIssues.length,0,'完整修订范围本身截断原表时仍不可扩大核对');
    panel.draft.action='correct_text';panel.context.source_kind='submission';assert.equal(panel.relatedRepairIssues.length,0);
    console.log('PASS explicit related field selection, preservation and source/action scope'); }
  { const numeric=fixture(); numeric.context.issues[0].code='numeric_uncertain';
    assert.equal(numeric.actions.length,0);
    numeric.context.issues[0].numeric_text_review_allowed=true;
    assert.deepEqual(Array.from(numeric.actions,a=>a.value),['correct_text']);
    assert.equal(numeric.draft.numeric_text_verified,false); }
  { const numeric=fixture(); assert.equal(numeric.draft.numeric_text_verified,false);
    numeric.draft.numeric_text_verified=true; let submitted;
    save=async(...args)=>{submitted=args[3];return {data:{revision:1,resolved_issue_keys:['i1','numeric']}}};
    await numeric.save(); assert.equal(submitted.items[0].numeric_text_verified,true);
    assert.equal(numeric.context.items[0].numeric_text_verified,true);
    options.watch.projectId.call(numeric);assert.equal(numeric.draft.numeric_text_verified,false); }
  let p=fixture(), wait=deferred();save=()=>wait.promise;
  const pending=p.save();p.draft.text='continued typing';wait.resolve({data:{revision:1}});await pending;
  assert.equal(p.context.revision,1);assert.equal(p.context.items[0].text,'corrected');assert.equal(p.draft.text,'continued typing');assert(p.dirty);
  p=fixture();save=async()=>{throw Error('409 stale')};await p.save();assert.equal(p.draft.text,'corrected');assert(p.dirty);assert(p.error.includes('409'));
  p=fixture();wait=deferred();save=()=>wait.promise;const oldSave=p.save();p.projectId='p2';options.watch.projectId.call(p);wait.resolve({data:{revision:4}});await oldSave;assert.equal(p.context,null);assert.equal(p.saving,false);assert.equal(p.draft.text,'');
  p=fixture();let first=deferred(),second=deferred(),count=0;image=()=>++count===1?first.promise:second.promise;
  const oldImage=p.loadImage(),newImage=p.loadImage();second.resolve({data:{marker:'new'}});await newImage;first.resolve({data:{marker:'old'}});await oldImage;assert.equal(p.preview.marker,'new');
  p=fixture();p.readiness={blocking_issues:Array.from({length:300},(_,i)=>({issue_key:String(i)}))};const all=[];for(let i=1;i<=15;i++){p.blockingIndex=i;all.push(...p.blockingPage.map(x=>x.issue_key));}assert.equal(new Set(all).size,300);
  p=fixture();p.$confirm=async()=>{throw Error('cancel')};p.visible=true;await p.close();assert.equal(p.visible,true);assert.equal(p.draft.text,'corrected');
  p=fixture();assert.equal(p.regionStyle.left,'10%');assert.equal(p.regionStyle.top,'20%');assert(!p.actions.some(a=>a.value==='confirm'));
  p=fixture();p.context.issues[0].code='text_assembly_unresolved';assert(p.actions.some(a=>a.value==='correct_text'));assert(!p.actions.some(a=>['confirm','irrelevant_region'].includes(a.value)));
  p.context.issues[0].repair_bbox_pdf=[0,0,50,50];p.context.issues[0].repair_table_index=0;
  assert(p.actions.some(a=>a.value==='correct_table'));assert(!p.actions.some(a=>a.value==='correct_text'));assert.equal(p.regionStyle.width,'50%');
  p.context.issues[0].code='ocr_quality';p.context.issues[0].confirm_allowed=true;
  assert(p.actions.some(a=>a.value==='correct_table'));assert(p.actions.some(a=>a.value==='confirm'));assert(!p.actions.some(a=>a.value==='correct_text'));
  p.context.issues.push({...p.context.issues[0],issue_key:'related',code:'ocr_coverage',bbox_pdf:[10,20,30,40]});
  p.context.issues.push({...p.context.issues[0],issue_key:'outside',bbox_pdf:[70,70,90,90]});
  assert.deepEqual(Array.from(p.relatedRepairIssues,i=>i.issue_key),['related']);
  p.toggleRelatedIssue('related',true);assert.equal(p.draft.related_issues[0].reason,'');
  p.toggleRelatedIssue('outside',true);assert.equal(p.draft.related_issues.length,1);
  p.toggleRelatedIssue('related',false);assert.equal(p.draft.related_issues.length,0);
  p=fixture();p.context.issues.push({...p.context.issues[0],issue_key:'covered'});save=async()=>({data:{revision:1,resolved_issue_keys:['i1','covered']}});await p.save();
  assert(p.context.issues.every(i=>i.resolved));p.selectedKey='covered';assert.equal(p.actions.length,0);p.selectedKey='i1';assert(p.actions.length>0);
  p=fixture();p.snapshot=JSON.stringify(p.draft);const reference={...p.context,source_kind:'reference',doc_id:'ref1'};
  let calls=0;sourceRead=async(project,kind,id)=>{calls++;assert.equal(project,'p1');assert.equal(kind,'reference');assert.equal(id,'ref1');return {data:reference};};
  image=async()=>({data:{page_bbox:[0,0,100,100]}});await p.openSource('reference','ref1');
  assert.equal(p.sourceTarget.doc_id,'ref1');assert(p.visible);assert.equal(p.selectedKey,'i1');assert.equal(p.readiness,null);
  p.draft.reason='unsaved';p.$confirm=async()=>{throw Error('cancel')};await p.openSource('reference','ref2');assert.equal(calls,1);assert.equal(p.context.doc_id,'ref1');assert.equal(p.draft.reason,'unsaved');
  p=fixture();p.snapshot=JSON.stringify(p.draft);wait=deferred();sourceRead=()=>wait.promise;const oldSource=p.openSource('reference','ref1');await Promise.resolve();await Promise.resolve();p.projectId='p2';options.watch.projectId.call(p);wait.resolve({data:reference});await oldSource;assert.equal(p.context,null);assert.equal(p.visible,false);
  p=fixture();p.context.issues[0].code='text_assembly_unresolved';p.context.issues[0].repair_bbox_pdf=[0,0,90,90];p.context.issues[0].repair_table_indices=[0,1];
  p.context.original_chunks[0].tables=['LEFT','RIGHT'].map(text=>({cells:[{row:0,column:0,rowspan:1,colspan:1,text}]}));
  p.setIssue('i1');assert.equal(p.draft.tables.length,2);assert(!p.draft.tables[0].verified);assert.equal(p.editingTable.cells[0].text,'LEFT');
  p.tableCursor=1;assert.equal(p.editingTable.cells[0].text,'RIGHT');assert(!p.dirty);p.editingTable.cells[0].text='RIGHT EDIT';assert.equal(p.draft.tables[0].table.cells[0].text,'LEFT');assert(p.dirty);
  p=fixture();p.context.items=[{...p.draft,issue_key:'i1'}];p.snapshot=JSON.stringify(p.draft);p.context.revision_error={code:'parse_revision_invalid'};
  let revoked;save=async(...args)=>{revoked=args[3];return {data:{revision:2,resolved_issue_keys:[]}}};
  await p.revoke(true);assert.equal(revoked.items.length,0);assert.equal(p.context.items.length,0);assert(!p.context.revision_error);assert(!p.context.issues[0].resolved);assert(!p.dirty);
  p=fixture();p.context.items=[{...p.draft,issue_key:'i1'}];p.snapshot=JSON.stringify(p.draft);save=async()=>{throw Error('409 conflict')};await p.revoke(false);assert.equal(p.context.items.length,1);assert(p.error.includes('409'));
  p=fixture();p.context.items=[{...p.draft,issue_key:'i1'}];p.snapshot=JSON.stringify(p.draft);p.$confirm=async()=>{throw Error('cancel')};let attempted=0;save=async()=>{attempted++};await p.revoke(true);assert.equal(attempted,0);assert.equal(p.context.items.length,1);
  p=fixture();p.context.items=[{...p.draft,issue_key:'i1'}];p.snapshot=JSON.stringify(p.draft);wait=deferred();save=()=>wait.promise;const revoking=p.revoke(true);await Promise.resolve();p.draft.text='new draft during revocation';wait.resolve({data:{revision:2,resolved_issue_keys:[]}});await revoking;assert.equal(p.draft.text,'new draft during revocation');assert(p.dirty);
  p=fixture();p.context.source_kind='application_form';p.context.issues[0].code='field_region_crossing';
  p.context.issues[0].field_options=[{item_no:6,title:'药品通用名称'}];
  assert.deepEqual(Array.from(p.actions,a=>a.value),['correct_text']);
  p.draft.target_item_no=6;let assignmentPayload;
  save=async(project,kind,doc,payload)=>{assignmentPayload=payload;return {data:{revision:1,resolved_issue_keys:['i1']}}};
  await p.save();assert.equal(assignmentPayload.items[0].target_item_no,6);assert(!p.dirty);
  p.setIssue('i1');assert.equal(p.draft.target_item_no,6);
  p.draft.field_assignments=[{target_item_no:6,text:'first'},{target_item_no:6,text:'second'}];
  p.draft.text='first\nsecond';p.draft.all_text_verified=true;
  await p.loadImage();await p.save();assert.equal(assignmentPayload.items[0].field_assignments.length,2);
  p.setIssue('i1');assert.equal(p.draft.field_assignments[1].text,'second');assert(p.draft.all_text_verified);
  p.context.source_kind='submission';assert.equal(p.actions.length,0);
  console.log('PASS 16 groups: existing 15 plus application field assignment and replay');
})().catch(e=>{console.error(e);process.exit(1)});
