CREATE TABLE IF NOT EXISTS `runtime_task` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `task_id` VARCHAR(128) NOT NULL,
  `domain` VARCHAR(64) NOT NULL,
  `task_type` VARCHAR(64) NOT NULL DEFAULT 'run',
  `project_id` VARCHAR(64) NOT NULL DEFAULT '',
  `run_id` VARCHAR(64) NULL,
  `source_doc_id` VARCHAR(256) NULL,
  `section_id` VARCHAR(128) NULL,
  `status` VARCHAR(32) NOT NULL DEFAULT 'pending',
  `message` TEXT NULL,
  `payload_json` LONGTEXT NULL,
  `result_json` LONGTEXT NULL,
  `logs_json` LONGTEXT NULL,
  `log_offset` INT NOT NULL DEFAULT 0,
  `error_message` TEXT NULL,
  `worker_id` VARCHAR(128) NULL,
  `heartbeat_at` DOUBLE NULL,
  `created_at` DOUBLE NOT NULL,
  `updated_at` DOUBLE NOT NULL,
  `finished_at` DOUBLE NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uq_runtime_task_task_id` (`task_id`),
  KEY `ix_runtime_task_domain` (`domain`),
  KEY `ix_runtime_task_task_type` (`task_type`),
  KEY `ix_runtime_task_project_id` (`project_id`),
  KEY `ix_runtime_task_run_id` (`run_id`),
  KEY `ix_runtime_task_source_doc_id` (`source_doc_id`),
  KEY `ix_runtime_task_section_id` (`section_id`),
  KEY `ix_runtime_task_status` (`status`),
  KEY `ix_runtime_task_worker_id` (`worker_id`),
  KEY `ix_runtime_task_heartbeat_at` (`heartbeat_at`),
  KEY `ix_runtime_task_updated_at` (`updated_at`),
  KEY `ix_runtime_task_finished_at` (`finished_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
